MusicMBundle_homepage:
    pattern:  /
    defaults: { _controller: MusicMBundle:Page:index }
    requirements:
        _method:  GET

MusicMBundle_charts:
    pattern: /charts
    defaults: { _controller: MusicMBundle:Page:charts }
    requirements:
        _method: GET

MusicMBundle_addtrack:
    pattern: /addtrack
    defaults: { _controller: MusicMBundle:Page:addtrack }
    requirements:
        _method: GET|POST

MusicMBundle_contact:
    pattern: /contact
    defaults: { _controller: MusicMBundle:Page:contact }
    requirements:
        _method: GET

MusicMBundle_Track_show:
    pattern: /track/{id}
    defaults: { _controller: MusicMBundle:Track:show }
    requirements:
        _method: GET|POST
        id: \d+

MusicMBundle_addsong:
    pattern: /addsong
    defaults: { _controller: MusicMBundle:Page:addsong }
    requirements:
        _method: GET|POST

MusicMBundle_Song_show:
    pattern: /song/{id}
    defaults: { _controller: MusicMBundle:Song:show }
    requirements:
        _method: GET
        id: \d+

MusicMBundle_Profile_show:
    pattern: /profiles/{slug}
    defaults: { _controller: MusicMBundle:Profile:show }
    requirements:
        _method: GET

MusicMBundle_Song_addTrackToSong:
    pattern: /addTrackToSong
    defaults: { _controller: MusicMBundle:Song:addTrackToSong }
    requirements:
       _method: GET|POST
       